FROM ubuntu:latest

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y golang-go

ENV GO111MODULE=off

# Build binary
RUN CGO_ENABLED=0 go build -o calculator .

# Run binary
ENTRYPOINT ["./calculator"]
