#####################BASE Image#####################
#stage 1: build the applciation
FROM ubuntu:latest as build
WORKDIR /app
RUN  apt-get update && apt-get install -y golang-go
COPY . .
ENV GO111MODULE=off
RUN CGO_ENABLED=0 go build -o calculator .
#ENTRYPOINT [ "/app" ] --> this one we are giving in the final stage
#Binary file will be created in the /app directory from the above commands.

#######Here starts the Multistaging Build#############
FROM scratch
WORKDIR /app

# Copy the compiled binary from the build stage
#COPY --from=build /app /app
COPY --from=build /app/calculator .

# Set the entrypoint for the container to run the binary
ENTRYPOINT ["./calculator"]
